= Networkd-broker
:toc:
:toc-placement!:

image:https://img.shields.io/github/v/tag/bpetlert/networkd-broker?include_prereleases&label=release&style=flat-square[Release,link=https://github.com/bpetlert/networkd-broker/releases/latest]
image:https://img.shields.io/aur/version/networkd-broker?style=flat-square["AUR: networkd-broker",link=https://aur.archlinux.org/packages/networkd-broker/]
image:https://img.shields.io/github/license/bpetlert/networkd-broker?style=flat-square["License: MIT",link=./LICENSE]

The networkd-broker is an event broker daemon for systemd-networkd.
It will execute scripts in the `/etc/networkd/broker.d/<STATE>.d` directory in alphabetical order in response to network events.

toc::[]

This work is based on https://gitlab.com/craftyguy/networkd-dispatcher[networkd-dispatcher], written in Rust, for the purpose of reducing runtime dependencies.
This also helps reduce memory footprint (~30MB &longrightarrow;
~8MB) and improve startup time (~30secs ⟶ ~1sec for spinning hard disk drive).

== Installation

=== Arch Linux

It is available on AUR as https://aur.archlinux.org/packages/networkd-broker/[networkd-broker].
To build and install arch package from GIT source:

[source,shell]
----
$ git clone https://github.com/bpetlert/networkd-broker.git
$ cd networkd-broker
$ makepkg -p PKGBUILD.local
$ pacman -U networkd-broker-xxxx-1-x86_64.pkg.tar
----

Then enable/start networkd-broker.service

[source,shell]
----
$ systemctl enable networkd-broker.service
$ systemctl start networkd-broker.service
----

== Configuration

To change the options of networkd-broker service e.g. enable debug, run `systemctl edit networkd-broker.service`

./etc/systemd/system/networkd-broker.service.d/override.conf
[source,ini]
----
[Service]
Environment='RUST_LOG=networkd_broker=debug'
----

Or enable `--run-startup-triggers`

./etc/systemd/system/networkd-broker.service.d/override.conf
[source,ini]
----
[Service]
ExecStart=
ExecStart=/usr/bin/networkd-broker --run-startup-triggers
----

== Usage

The scripts for any network event need to be putted (or symlink) in its corresponding directory as shown below.
Each script must be a regular executable file owned by root.
The default execution timeout of each script is 20 seconds.
It can be overridden by `--timeout` option in service configuration.
Any of the scripts which end with '-nowait' is run immediately, without waitting for the termination of previous scripts.

[source]
----
/etc/networkd
└── broker.d
    ├── carrier.d
    ├── degraded.d
    ├── dormant.d
    ├── no-carrier.d
    ├── off.d
    └── routable.d
----

The scripts are run in alphabetical order, one at a time with two arguments and a set of environment variables being passed.
Each script run asynchronously from `networkd-broker` process.

|===
| Argument | Description

| `STATE`
| Current link status is one of the following: `carrier`, `degraded`, `dormant`, `no-carrier`, `off`, `routable`;
see `man networkctl` for more details.

| `IFACE`
| Link name that operation just happened on
|===

The following environment variables are being passed to each script:

|===
| Variable | Description

| `NWD_DEVICE_IFACE`
| Link name that operation just happened on, same value as `IFACE`

| `NWD_BROKER_ACTION`
| Current link status, same value as `STATE`

| `NWD_JSON`
| All the link details are encoded in JSON format.
|===

=== Example script

The script below activate/deactivate https://wiki.archlinux.org/index.php/Chrony[Chrony] correspond to link state of `wlp3s0` link.
This script must be put (or symlink) in `/etc/networkd/broker.d/routable.d`, and `/etc/networkd/broker.d/no-carrier.d`.

.chrony-switch
[source,bash]
----
#!/usr/bin/env bash

STATE=$1
IFACE=$2

if [[ $IFACE != "wlp3s0" ]]; then
    exit 0
fi

if [[ "$STATE" = "routable" ]]; then
  chronyc online > /dev/null
  chronyc burst 4/4 > /dev/null
  sleep 10
  chronyc makestep > /dev/null
  echo "Activate chrony"
elif [[ "$STATE" = "no-carrier" ]]; then
  chronyc offline > /dev/null
  echo "Deactivate chrony"
fi
----

== Design

[link=https://raw.githubusercontent.com/bpetlert/networkd-broker/main/docs/assets/networkd-broker.svg?sanitize=true&raw=true]
image::https://raw.githubusercontent.com/bpetlert/networkd-broker/main/docs/assets/networkd-broker.svg?sanitize=true&raw=true[Sequence Diagram]

== License

https://github.com/wavexx/networkd-notify[networkd-notify]: +
Copyright (C) 2016 mailto:wavexx@thregr.org[Yuri D'Elia]

https://gitlab.com/craftyguy/networkd-dispatcher[networkd-dispatcher]: +
Copyright (C) 2018 mailto:clayton@craftyguy.net[Clayton Craft]

https://github.com/bpetlert/networkd-broker[networkd-broker]: +
Copyright (C) 2019 mailto:bpetlert@gmail.com[Bhanupong Petchlert]

link:./LICENSE[GNU GPLv3] +
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.
If not, see https://www.gnu.org/licenses/.
