@startuml networkd-broker

skinparam BoxPadding 10

participant DBus
box "networkd-broker" #LightBlue
participant Broker
participant Script
participant Environments
participant Launcher
end box
participant System

autonumber

== Initialization ==
Launcher -> Launcher ++ : recv
Broker -> Broker ++ : listen

== Receive Signal ==
DBus -> Broker ++ : signal
Broker -> Script ++ : get script list
return script list
Broker -> Environments ++ : fetch env
return env
Broker -> Launcher --: send script list to queue
Launcher -> System ++ : execute script
return done

@enduml
