@startuml networkd-broker

skinparam defaultFontName "Helvetica"
skinparam defaultFontSize 13
skinparam defaultFontColor black
skinparam BackgroundColor Azure
skinparam ParticipantPadding 20
skinparam BoxPadding 10
skinparam shadowing false

participant "**DBus**" as DBus

box "networkd-broker" #DeepSkyBlue
participant Broker
participant ScriptBuilder
participant Script
participant Launcher
end box

participant "**System**" as System

autonumber

== Initialization ==
Launcher ->> Launcher ++ : wait for new script
Broker ->> Broker ++ : listen to link events

== Receive Signal ==
DBus -> Broker ++ : link event signal
Broker -> ScriptBuilder ++ : build scripts correspond\nto link event
ScriptBuilder -> Script ** : create
return scripts
Broker ->> Launcher --: send scripts to queue

== Execute Script Queue ==
Launcher ->> System ++ : execute script
return done

@enduml
