use zbus::dbus_proxy;

/// DBus interface proxy for: `org.freedesktop.network1.Manager`
///
/// This code was generated by `zbus-xmlgen` `2.0.1` from DBus introspection data.
/// Source: `Interface '/org/freedesktop/network1' from service 'org.freedesktop.network1' on system bus`.
#[dbus_proxy(
    interface = "org.freedesktop.network1.Manager",
    default_service = "org.freedesktop.network1",
    default_path = "/org/freedesktop/network1"
)]
pub trait NetworkManager {
    /// ListLinks method
    fn list_links(&self) -> zbus::Result<Vec<(i32, String, zbus::zvariant::OwnedObjectPath)>>;

    /// DescribeLink method
    fn describe_link(&self, ifindex: i32) -> zbus::Result<String>;
}
